language: java
install: true
jdk:
- oraclejdk8
script:
- "./gradlew build -s"
deploy:
  provider: releases
  file: build/libs/*.jar
  api_key: $GITHUB_KEY
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: "X69P/YCeZ54xksYYPCjdiHqJUW5qGgsL5ZwoPzhR5lZACLOGsuwqDwqO9yiPxgFLP+3v11ow1hmYJZ3XURq3lIHqt+w2WXRFjWHPkbUfGSfx2YAeyDBRmUAH2gvzKzZySXmnoEMM089gyfOefYixPGgOtPAFg3Yop7fSgYuN6/cpagDu+i1UcsNisAjeXJzjT1AQkmQaHW0WSvVL+9lqFg2wZtKn1FCKgpRYtcwYLo+khsfjcw5ws8Oisk+OvVGR+xyH1tYMNBcg2QeRFQ+z1IC2/xc1BkZtEimOT2E3trp/Lu17MBtYi2eLQTyA8+R8xnc/cIXiZzMwT5xLlen38W+4R6xV1A+wTo5nx262DdJZepevIIm+B7X9fuQGzygBV5or3AyyWAE7MEnL8BqgU/xQFDkKUA3xHmV+6PSSt/H2Hdall7Akv4QTqPlN9bhDrihs24vCE3KfGo7eN46ux9gfeA7K4WmM0tnFq16uc51NWQwXT/35SfkBXvaqz23NOb+xc1zx8MI0UpzryNy3wXNn352tjNcJwYAIlWndTzXjQfTBxNxEGrcEt+2UbT9AP2EgWVxfSsR9fRqjdlG8nASAzGNoUeLxm351YxK97ZoaI9v/KXR6QeA7PtTzZQNQqEXXMTaiDW3hG/m65jzWa1r+ENtQWENCECgnsaHDhlQ="
